services: 
    - docker

before_install:
    - "mv .env1 .env"
    
before_script:
    - docker-compose up -d --build

script:
    - "docker-compose run featherlight pytest -sx"

# script:
#     - docker-compose run featherlight pytest 
