version: '3'
services: 
    btcd:
        image: btcd
        build: 
            context: 'btcd/'
        volumes:
            # - shared:/rpc
            - /mnt/volume_tor1_01/bitcoin:/data
            - ./btcd/btcd.conf:/root/.btcd/btcd.conf
        environment:
            - RPCUSER
            - RPCPASS
            - NETWORK
            - DEBUG
            - MINING_ADDRESS
    
    lnd:
        image: lnd
        build:
            context: 'lnd/'
        volumes: 
            # - shared:/rpc
            - /mnt/volume_tor1_01/lnd:/root/.lnd
            - ./lnd/lnd.conf:/root/.lnd/lnd.conf
        environment: 
            - RPCUSER
            - RPCPASS
            - NETWORK
            - CHAIN
            - DEBUG
        depends_on: 
            - btcd

    ariadne:
        image: graphlnd
        build: 
            context: 'ariadne/'
        volumes: 
            - ./ariadne/code/:/app/code
            - /mnt/volume_tor1_01/lnd:/root/.lnd
            # - shared:/rpc
        ports:
            - '127.0.0.1:5001:5001'
        depends_on: 
            - lnd
            - redis

    redis:
        image: redis:alpine
        volumes: 
            - /mnt/volume_tor1_01/redis:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf


volumes:
    # shared:
    #     driver: local

    lnd:
        driver: local

    bitcoin:
        driver: local

    redis:
        driver: local
