version: '3'
services: 
    btcd:
        image: btcd:latest
        build: 
            context: 'btcd/'
        volumes:
            # - shared:/rpc
            - ${BITCOIN_VOL}:/data
            - ./btcd/btcd.conf:/root/.btcd/btcd.conf
        restart: unless-stopped
        env_file: 
            - global.env
    
    lnd:
        image: lnd:latest
        build:
            context: 'lnd/'
        volumes: 
            # - shared:/rpc
            - ${LND_VOL}:/root/.lnd
            - ${BITCOIN_VOL}:/bitcoindata
            - ./lnd/lnd.conf:/root/.lnd/lnd.conf
        restart: unless-stopped
        env_file: 
            - global.env
        depends_on: 
            - btcd
        ports:
            - '9735:9735'

    ariadne:
        image: graphlnd:latest
        build: 
            context: 'ariadne_server/'
        volumes: 
            - ./ariadne_server/:/app
            - ${LND_VOL}:/root/.lnd
        ports:
            - '5001:5001'
        depends_on: 
            - lnd
            - redis
        restart: unless-stopped
        env_file: 
            - global.env

    redis:
        image: redis:alpine
        volumes: 
            - ${REDIS_VOL}:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        restart: unless-stopped
        env_file: 
            - global.env

    postgres:
        image: postgres:alpine
        volumes:
            - ${POSTGRES_VOL}:/var/lib/postgresql/data
        restart: unless-stopped
        env_file: 
            - global.env
        ports: 
            - '5432:5432'
            

