version: '3'
services: 
    btcd:
        image: btcd
        build: 
            context: 'btcd/'
        volumes:
            # - shared:/rpc
            - /mnt/volume_tor1_01/bitcoin:/data
            - ./btcd/btcd.conf:/root/.btcd/btcd.conf
        env_file: 
            - global.env
    
    lnd:
        image: lnd
        build:
            context: 'lnd/'
        volumes: 
            # - shared:/rpc
            - /mnt/volume_tor1_01/lnd:/root/.lnd
            - /mnt/volume_tor1_01/bitcoin:/bitcoindata
            - ./lnd/lnd.conf:/root/.lnd/lnd.conf
        env_file: 
            - global.env
        depends_on: 
            - btcd

    ariadne:
        image: graphlnd
        build: 
            context: 'ariadne/'
        volumes: 
            - ./ariadne/:/app/
            - /mnt/volume_tor1_01/lnd:/root/.lnd
        ports:
            - '5001:5001'
        depends_on: 
            - lnd
            - redis
        env_file: 
            - global.env

    redis:
        image: redis:alpine
        volumes: 
            - /mnt/volume_tor1_01/redis:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        env_file: 
            - global.env

#
# volumes:
    # shared:
        #driver: local

